### PR TITLE
Drawn board at /games/show

### PR DESCRIPTION
**Pull request by Quavacle**
Board should be resizing to any window size (at least that I tested). Added a hover class just to make sure each div was selectable (not just the contents).

### CODE REVIEW

**Comment by jmoglesby** [comment]
> It looks like you took rspec out of your gem file for some reason. I believe we had decided to use rspec for our test driven develop. Other than that it looks good.

I don't think he took it out, I'm guessing he just branched without running `$ bundle install`. The `Gemfile` is untouched in his branch, it's just the `Gemfile.lock` that is missing `RSpec`. As soon as you run `$ bundle install` when there are new gems in the `Gemfile`, bundler adds them to the lock file.

**Comment by Quavacle** [comment]
On our current master branch I'm not seeing Rspec in the gemfile, only in the gemfile.lock. So when I pull from origin I have to rm the lock file and do a bundle install. Am I missing something?

**Comment by jmoglesby** [comment]
No, @Quavacle, you're not missing anything -- I think somewhere in the process of Nicholas trying to fix the issue he ran into with the `gemfile.lock` the `rspec` gem accidentally got left out of the `Gemfile`. We don't really have much functionality to test yet, so it's not a big deal, but we definitely need to get our master branch smoothed out. If you'd like to do that now by adding `gem rspec` back to the `Gemfile` for this merge, that would be fine.

**Comment by Quavacle** [comment]
Alright, added RSpec back in to the gemfile, as well as updated coordinates as a data type for easier access down the line

**Pull request merged**
