### PR TITLE
FactoryBot

### PR DESCRIPTION
**Pull request by Quavacle**
Added in FactoryBot for unit testing and Database Cleaner to clear test database. Needs a bundle install and everything should be up and running.

Added in 2 simple tests to ensure functionality.

To add a user to any test:
FactoryBot.create(:user)

### CODE REVIEW

**Comment by Quavacle** [comment]
Pushed another commit to this branch accidentally, but it all seems correct to me.
I took a step back from the controllers and went with a TDD approach instead of (awkwardly) building front end to back end. I implemented tests (all passing) for piece creation and updating.

@jmoglesby I figured out how to pass my JSON through just the games controller to update the pieces, I failed to add in to the games object the accepts_nested_attributes_for attribute. Hopefully when I implement my standing front-end it should avoid the ID problems I was having before.

**Comment by jmoglesby** [comment]
> I figured out how to pass my JSON through just the games controller to update the pieces, I failed to add in to the games object the accepts_nested_attributes_for attribute. Hopefully when I implement my standing front-end it should avoid the ID problems I was having before.

Awesome! Good to know. So if you add that rails method to the Games model, rails will automatically parse out a nested id (ie `games/:id/pieces/:id`) as a `piece_id`?

**Comment by Quavacle** [comment]
@jmoglesby Exactly. [This article explains it fairly simply](https://medium.com/@onyoo/why-accepts-nested-attributes-for-6ed190def58a)

**Comment by jmoglesby** [comment]
@Quavacle, I think maybe your bundler is going haywire with the rspec gem... do you see this in your local Gemfile?
image

There are 3 `gem 'rspec'` declarations there.

**Comment by Quavacle** [comment]
@jmoglesby That's so strange, it had one extra instance of RSpec in my local but not the spacing. Removed and committed. Hopefully.

**Pull request merged**
